In [4]:
import pandas as pd
import numpy as np
rng = np.random.default_rng()
f = rng.random((3,2))
f

array([[0.54851363, 0.10775003],
       [0.67909219, 0.12915236],
       [0.05389233, 0.04169439]])

In [5]:
rng = np.random.default_rng(123)
rng.normal(10, 5, 180)

array([ 5.05439325,  8.16106674, 16.43962631, 10.9698721 , 14.6011545 ,
       12.88551896,  6.81768177, 12.7097611 ,  8.41702274,  8.38805442,
       10.48583659,  2.37034797, 15.96083052,  6.64455162, 15.0013471 ,
       10.68160562, 17.6601654 ,  6.70015293,  8.44102572, 11.68884563,
       -1.03735549, 14.13960721, 17.70815197, 15.63403397, 13.77384822,
        9.27011053, 16.40951114, 15.37015311, 11.96310422, 10.02557156,
        8.19116564,  3.84883902, 16.13114646, -0.86021943,  8.14926327,
       10.82190035, 14.29940592, 18.80830618, 14.96661888,  8.54239287,
       13.64063779,  3.69199842, 17.14969263,  9.21762338,  6.63120425,
        6.8046995 ,  9.69319336,  8.03607539, 21.44954974,  6.40909426,
       10.16303872, 10.14024948, 10.14136061, 10.27672931,  7.59218571,
        7.0829625 ,  5.68919749,  2.55912693, 11.08153417, 14.92188175,
        7.28457929,  7.2069248 ,  8.41758585,  7.69680129,  2.81865125,
       16.82554016, 12.19499944,  6.44152486, 11.48585881,  7.80

In [6]:
import numpy as np 
# 正規分布の乱数の絶対値を取る
positive_normal_random_numbers = np.ceil(np.abs(np.random.normal(10,5,180 * 5)))
print(positive_normal_random_numbers)


[17.  6.  2. 17.  4. 17. 14.  4. 15.  1. 15.  4.  8. 15.  6. 17. 10.  8.
  1. 10. 12. 14. 15. 10.  6. 10. 12.  9.  6.  7.  3. 13. 11.  6. 16. 15.
 15.  6.  3. 14. 14. 20.  4.  4. 12.  9.  7.  7.  5. 14. 14. 13. 20. 22.
 20. 12.  9. 21. 18. 16. 21. 13.  2. 13.  9.  7. 12.  5.  9. 10. 10. 12.
 14.  3.  7.  7. 12. 13.  5.  8. 13. 13. 13. 14. 11. 11.  9. 20. 14. 15.
  4. 22. 13.  8. 20. 12. 10. 16. 12. 13. 10. 14.  6.  2. 14. 13. 15. 16.
 12. 16.  7.  7.  7. 23. 13. 10.  4. 20. 10.  7. 15. 13. 16.  1.  5.  9.
 12. 19.  9.  7. 12.  5. 19.  6.  8.  5. 12.  8. 20.  3. 12.  2. 14.  5.
 10.  3. 20.  4. 18.  5.  9.  6.  3.  9.  9.  1. 17.  2.  6.  3.  6.  5.
 13. 10.  6.  5.  7.  9.  3. 13. 10.  5. 15. 14. 11. 13. 17. 12. 11.  7.
 10. 20. 13.  5.  3. 13. 13. 13.  3. 13.  5.  9. 15. 14.  8. 11. 15. 15.
 14. 14.  9. 14.  9.  8.  7.  8.  5. 14. 15.  2. 16.  1. 12.  6. 14. 13.
 14.  8.  5. 17.  8.  8.  6.  6. 14. 15.  7. 11. 16.  9.  2.  5. 11. 17.
  6. 16. 10. 15. 10. 15.  6. 15. 24. 21.  7. 15. 13

In [27]:
import numpy as np 
# 正規分布の乱数の絶対値を取る
positive_normal_random_numbers = np.floor(np.abs(np.random.normal(1,0.3,180)))
print(positive_normal_random_numbers)

正規分布の絶対値を取った0以上の乱数: [0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1.
 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0.
 0. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0.
 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1.
 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0.]


In [29]:
import numpy as np 
# 正規分布の乱数の絶対値を取る
positive_normal_random_numbers = np.floor(np.abs(np.random.normal(35,10,180)))
print(positive_normal_random_numbers)

[39. 41. 48. 35. 40. 36. 38. 20. 39. 17. 24. 37. 22. 33. 54. 30. 32. 27.
 38. 22. 30. 35. 31. 23. 48. 37. 44. 45. 24. 41. 44. 29. 46. 31. 39. 47.
 30. 29. 37. 31. 35. 38. 17. 29. 20. 18. 21. 33. 45. 40. 41. 38. 26. 12.
 53. 25. 41. 46. 14. 39. 12. 28. 30. 33. 52. 40. 38. 26. 44. 25. 46. 28.
 46. 54. 33. 24. 33. 42. 40. 59. 65. 27. 33. 35. 27. 19. 44. 42. 28. 26.
 34. 41. 36. 30. 39. 47. 29. 39. 37. 55. 33. 33. 30. 25. 20. 40. 47. 41.
 31. 28. 50. 55. 37. 24. 25. 32. 15. 43. 19. 42. 39. 50. 37. 51. 34. 44.
 37. 29. 36. 49. 41. 56. 40. 40. 29. 24. 40. 15. 29. 22. 38. 47. 32. 32.
 24. 34. 37. 37. 16. 53. 35. 29. 39. 41. 34. 40. 51. 33. 34. 37. 44. 24.
 39. 40. 40. 45. 36. 33. 28. 47. 45. 40. 18. 35. 31. 47. 37. 43. 30. 15.]


In [7]:
import numpy as np 
# 正規分布の乱数の絶対値を取る
positive_normal_random_numbers = np.ceil(np.abs(np.random.normal(10,5,180 * 5)))
print(positive_normal_random_numbers)

[12. 16. 11.  8. 13.  8. 12.  1.  8. 18. 11. 13. 11.  8. 17.  2. 22.  8.
 10. 17. 10.  1. 13.  5. 20.  5. 21.  7.  9. 10. 10. 15. 16. 12. 17. 10.
 11.  8.  9.  7. 17. 15. 10. 21.  1. 13.  2. 11. 11.  2. 19. 17. 11.  7.
  8. 15. 19.  2.  9. 13. 17. 10.  8. 15. 14.  9. 13.  2. 15. 20. 13. 16.
 15. 12. 10. 13.  9.  5. 12. 10.  9. 13. 12. 15. 14. 11.  8.  4.  1. 13.
 14.  7. 18. 12. 20. 14.  7. 10.  6.  5. 17.  5.  4. 16.  8.  7.  8. 10.
  4.  4. 10. 11.  9. 14. 18.  6.  8. 10.  3. 15.  8.  9.  9.  8. 20.  6.
 10.  1.  9. 10. 15. 11. 16.  3.  6. 11. 12. 17.  7. 13.  7.  5. 11.  7.
 15. 13.  8.  3. 10. 17.  9. 22. 10. 20.  9. 13. 17.  7.  9. 13.  7.  9.
  5. 10. 13. 12.  6.  3.  8. 14. 13. 15. 10.  4. 10.  5. 11. 22. 11.  7.
 20. 11. 12.  4.  3. 14.  5.  4. 17.  8. 11. 11.  8. 15. 17. 10. 11.  8.
  5.  7.  7. 14.  2.  3.  8.  6. 16. 18. 19. 11. 14. 13.  8. 10. 16.  9.
  8. 15. 15.  5. 15. 15.  5.  8. 14. 14. 11.  4. 10. 16.  7. 14. 14.  9.
  7.  6.  7.  8.  5.  8. 19. 17. 16. 13. 16.  7.  9

In [8]:
import numpy as np 
# 正規分布の乱数の絶対値を取る
positive_normal_random_numbers = np.ceil(np.abs(np.random.normal(10,5,180 * 5)))
print(positive_normal_random_numbers)

[ 9.  7.  9. 11. 13. 12.  7. 16. 17. 16.  6. 15. 14. 11. 14.  8. 17. 16.
 14. 13. 16. 10. 10.  5. 15. 11.  7. 14.  5.  8. 12. 15.  7. 17.  8.  2.
  9.  5. 12.  7. 15. 13. 10.  7. 14. 11. 12.  7. 13. 16.  6.  4.  6. 23.
 14. 16.  3. 13.  2. 16. 19.  8. 10. 13. 11.  4. 14. 15.  1. 12. 12.  3.
  9. 11.  8. 14. 15. 14. 12. 15. 10. 10. 12. 10. 18.  3.  8.  6. 14.  2.
 20.  2.  8. 15.  5. 18. 13. 10. 12.  9.  1.  3.  5.  4. 18. 24.  8.  6.
  8. 18. 14. 12. 10. 16.  9. 17. 11. 11.  9. 19.  8. 11.  7.  6. 10. 12.
  9.  7.  5. 10. 17. 12.  9.  4. 15. 10. 11. 13. 11. 12.  3. 15.  7. 17.
  9. 10. 23. 20.  5.  5. 22. 21. 11. 18.  1.  8. 18. 12.  5. 15.  5. 10.
  9.  6.  8. 12. 15. 14.  5.  5.  8.  8.  5. 10.  6. 10. 12.  5.  8.  5.
  8. 12. 12.  8.  9.  9.  4. 13.  5. 17. 14.  8. 17.  9. 14.  9. 16.  8.
 16. 12. 11.  9. 14. 15. 10. 14. 20.  8.  8. 14.  5. 13. 13. 13. 11. 11.
 15. 11. 18.  5.  2. 14.  7. 10.  7. 10. 10.  8. 17.  6. 12. 17. 12.  9.
 11.  3. 16. 17. 15. 17.  8. 16. 21.  9. 12.  9. 12

In [9]:
import numpy as np 
# 正規分布の乱数の絶対値を取る
positive_normal_random_numbers = np.ceil(np.abs(np.random.normal(10,5,180 * 5)))
print(positive_normal_random_numbers)

[ 2.  9. 12.  9. 12. 13. 23. 12. 12. 14.  7. 11.  9. 17. 14.  8. 10. 10.
 10. 18. 10. 24.  2. 16. 11. 14. 25.  8.  2.  9.  2. 20. 15. 18. 14. 12.
 12.  8. 12. 13. 13. 23.  7.  9. 10. 15. 24. 16. 12. 10.  5.  8. 20.  3.
 16. 10. 12.  1. 12. 11. 11.  9.  3. 13. 12. 18.  7.  8.  9.  9.  9.  9.
 18. 10. 16. 13.  7.  3.  5. 16. 12. 16.  3. 18.  8. 10. 17. 13.  9.  6.
 10.  9. 10. 17.  7. 12.  8.  8.  9. 17. 14.  7. 16.  5.  8. 14.  7.  4.
 15.  2. 15. 12.  7.  7. 15. 12.  5.  6. 14.  6.  9.  9.  6.  9.  8.  5.
 13.  8. 16.  7. 10. 17. 19. 17.  7.  7. 10. 10. 11. 11. 15.  9. 14.  8.
  6. 19. 15. 13.  9.  9.  8.  4.  4. 14. 12. 10.  3. 12.  4.  4.  2.  3.
 13.  7. 19. 10. 15. 14. 12.  4.  4.  8.  8.  8. 14. 14. 12. 10.  7. 11.
 16. 13. 14. 12. 10. 13.  8. 13.  9. 12. 14. 19. 10.  8. 12. 19. 12. 10.
  5.  6. 10.  3. 25.  5.  9.  7.  2. 13. 17. 14. 12. 24. 11. 14.  9. 19.
 13. 12. 21. 12.  8. 11. 14. 18. 14.  8.  6. 12.  5. 15.  9.  9.  6.  8.
 11. 10.  6. 10. 14. 22.  9. 14. 12.  7. 13. 13.  2

In [10]:
import numpy as np 
# 正規分布の乱数の絶対値を取る
positive_normal_random_numbers = np.ceil(np.abs(np.random.normal(10,5,180 * 5)))
print(positive_normal_random_numbers)

[16.  8.  7. 13. 15. 13.  7.  8. 13.  3. 10.  7. 11. 10. 15. 15.  8. 14.
  6.  7.  8. 10.  3.  3. 12.  8. 15.  9. 12.  7. 12. 10.  6. 17.  9. 13.
  4. 12.  5. 10. 15.  5. 11.  4. 10. 12.  8. 10. 13. 12. 12. 21. 14. 16.
 11.  7.  8. 10.  9. 10.  5.  9.  2. 16. 21.  5. 12. 14. 10.  5.  8.  8.
 20. 12. 15.  5. 13. 14.  6. 16. 14. 10.  4.  6. 10. 24.  8. 11. 18.  8.
 16. 10. 14. 13.  6. 15. 12.  3.  5. 19.  9.  4. 12. 17.  6.  9.  6. 14.
  6. 10. 11.  7.  4.  2.  8. 14. 19.  9. 10. 17.  7. 13. 16. 10. 14. 12.
 10. 19.  9.  4.  5. 11. 16. 17. 17.  3.  9. 12. 10.  8. 18. 11. 20.  7.
 15. 12. 13.  2. 16.  9.  7. 13. 12. 19.  6. 15.  6. 11.  8. 14. 14. 15.
 19. 15.  4. 11. 11. 16.  2. 12. 18. 10. 15. 16. 13.  6. 15.  6. 15.  9.
  9. 17. 10. 10.  8. 10.  4.  8.  4. 11. 19.  6. 19. 12.  8.  8.  8.  3.
  2. 10. 12. 10. 10.  9. 11.  6. 14.  8. 11. 13. 17.  7. 10. 10.  3.  5.
 21. 15. 18.  2. 16.  7. 13.  9.  2. 15. 19. 12. 10.  8. 11.  8.  8.  2.
 11. 14.  5. 12. 22. 10. 24.  5. 13. 13. 13. 15. 10

In [25]:
import numpy as np 
# 正規分布の乱数の絶対値を取る



[ 7. 12. 12. ...  9. 11. 11.]
[2. 2. 1. ... 2. 1. 1.]
[28. 22. 27. ... 20. 30. 30.]


In [36]:
import pandas as pd
import numpy as np

# 2024-05
time_2405 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2405)
jender_2405 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2405)
age_2405 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2405)

data_2405 = np.vstack((time_2405, jender_2405, age_2405)).T

print(data_2405)

print(len(data_2405))

# 2024-06
time_2406 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2406)
jender_2406 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2406)
age_2406 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2406)

data_2406 = np.vstack((time_2406, jender_2406, age_2406)).T

print(data_2406)

print(len(data_2406))


# 2024-07
time_2407 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2407)
jender_2407 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2407)
age_2407 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2407)

data_2407 = np.vstack((time_2407, jender_2407, age_2407)).T

print(data_2407)

print(len(data_2407))


# 2024-08
time_2408 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2408)
jender_2408 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2408)
age_2408 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2408)

data_2408 = np.vstack((time_2408, jender_2408, age_2408)).T

print(data_2408)

print(len(data_2408))


# 2024-09
time_2409 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2409)
jender_2409 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2409)
age_2409 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2409)

data_2409 = np.vstack((time_2409, jender_2409, age_2409)).T

print(data_2409)

print(len(data_2409))


# 2024-10
time_2410 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2410)
jender_2410 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2410)
age_2410 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2410)

data_2410 = np.vstack((time_2410, jender_2410, age_2410)).T

print(data_2410)

print(len(data_2410))


# 2024-11
time_2411 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2411)
jender_2411 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2411)
age_2411 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2411)

data_2411 = np.vstack((time_2411, jender_2411, age_2411)).T

print(data_2411)

print(len(data_2411))


# 2024-12
time_2412 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2412)
jender_2412 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2412)
age_2412 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2412)

data_2412 = np.vstack((time_2412, jender_2412, age_2412)).T

print(data_2412)

print(len(data_2412))


# 2025-01
time_2501 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2501)
jender_2501 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2501)
age_2501 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2501)

data_2501 = np.vstack((time_2501, jender_2501, age_2501)).T

print(data_2501)

print(len(data_2501))


# 2025-02
time_2502 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2502)
jender_2502 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2502)
age_2502 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2502)

data_2502 = np.vstack((time_2502, jender_2502, age_2502)).T

print(data_2502)

print(len(data_2502))


# 2025-03
time_2503 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2503)
jender_2503 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2503)
age_2503 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2503)

data_2503 = np.vstack((time_2503, jender_2503, age_2503)).T

print(data_2503)

print(len(data_2503))


# 2025-04
time_2504 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2504)
jender_2504 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2504)
age_2504 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2504)

data_2504 = np.vstack((time_2504, jender_2504, age_2504)).T

print(data_2504)

print(len(data_2504))

# df = pd.DataFrame([[1, 2, 3], [3, 4]], columns=["滞在時間", "性別", "年齢"])
# pd.DataFrame(df)

[[13.  2. 32.]
 [13.  1. 28.]
 [11.  2. 45.]
 ...
 [18.  1. 36.]
 [12.  2. 44.]
 [ 6.  2. 38.]]
5400
[[11.  2. 48.]
 [ 7.  1. 43.]
 [ 2.  1.  4.]
 ...
 [ 3.  1. 38.]
 [18.  1. 46.]
 [ 7.  2. 47.]]
5400
[[ 7.  1. 40.]
 [20.  2. 35.]
 [ 6.  1. 45.]
 ...
 [ 5.  2. 35.]
 [ 9.  1. 35.]
 [13.  1. 34.]]
5400
[[17.  2. 42.]
 [ 6.  1. 23.]
 [12.  1. 25.]
 ...
 [10.  1. 45.]
 [14.  2. 38.]
 [13.  2. 44.]]
5400
[[ 6.  2. 33.]
 [17.  2. 50.]
 [ 7.  2. 39.]
 ...
 [25.  1. 62.]
 [13.  1. 19.]
 [11.  1. 46.]]
5400
[[ 9.  2. 38.]
 [10.  1. 51.]
 [ 5.  2. 15.]
 ...
 [17.  2. 37.]
 [ 9.  2. 29.]
 [13.  1. 26.]]
5400
[[ 8.  2. 26.]
 [18.  2. 30.]
 [10.  1. 37.]
 ...
 [10.  1. 43.]
 [ 8.  1. 36.]
 [ 7.  1. 29.]]
5400
[[14.  1. 48.]
 [12.  1. 33.]
 [16.  2. 32.]
 ...
 [ 1.  2. 23.]
 [13.  1. 36.]
 [ 5.  1. 35.]]
5400
[[10.  2. 39.]
 [ 5.  2. 38.]
 [ 6.  2. 62.]
 ...
 [16.  2. 35.]
 [10.  1. 21.]
 [ 1.  2. 46.]]
5400
[[15.  2. 28.]
 [16.  2. 43.]
 [14.  2. 46.]
 ...
 [17.  1. 26.]
 [14.  2. 44.]
 [ 7.  2. 3

In [4]:
import pandas as pd
import numpy as np

# 2024-05
time_2405 = np.ceil(np.abs(np.random.normal(10,5,180 * 30)))
# print(time_2405)
jender_2405 = np.ceil(np.abs(np.random.normal(1,0.3,180 * 30)))
# print(jender_2405)
age_2405 = np.ceil(np.abs(np.random.normal(35,10,180 * 30)))
# print(age_2405)

dataframe_2405 = pd.DataFrame({"time":time_2405, "gender":jender_2405, "age":age_2405})

print(dataframe_2405)

print(len(data_2405))

ModuleNotFoundError: No module named 'matplotlib'